version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: javad
      POSTGRES_PASSWORD: javad321!
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./book_records:/app/book_records
    depends_on:
      - postgres-db
    environment:
      - JDBC_URL=jdbc:postgresql://postgres-db:5432/library_db
      - DB_USER=javad
      - DB_PASSWORD=javad321!

volumes:
  pgdata: