services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: javad
      POSTGRES_PASSWORD: javad321!
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: javad321!
      MYSQL_DATABASE: library_db
      MYSQL_USER: javad
      MYSQL_PASSWORD: javad321!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  liquibase-postgres:
    image: liquibase/liquibase
    container_name: liquibase_postgres_container
    volumes:
      - ./changelog:/liquibase/changelog
    working_dir: /liquibase
    command:
      - liquibase
      - --changeLogFile=changelog/changelog.xml
      - --url=jdbc:postgresql://postgres:5432/library_db
      - --username=javad
      - --password=javad321!
      - update
    depends_on:
      - postgres

  liquibase-mysql:
    image: liquibase/liquibase
    container_name: liquibase_mysql_container
    volumes:
      - ./changelog:/liquibase/changelog
      - ./lib/mysql-connector-j-8.0.33.jar:/liquibase/lib/mysql-connector-j-8.0.33.jar
    working_dir: /liquibase
    command:
      - liquibase
      - --changeLogFile=changelog/changelog.xml
      - --url=jdbc:mysql://mysql:3306/library_db
      - --username=javad
      - --password=javad321!
      - update
    depends_on:
      - mysql

  library-management-dao:
    image: library-management-dao-app
    container_name: library-management-dao
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mysql
      - liquibase-postgres
      - liquibase-mysql
    volumes:
      - ./lib:/library-management-dao/lib
    command: ["java", "-cp", "/library-management-dao/lib/*:/library-management-dao/library-management-dao.jar", "main.Main"]

volumes:
  postgres_data:
  mysql_data: